# fly.toml app configuration file generated for flugo-api on 2023-06-07T21:33:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flugo-api"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "postgres://postgres:bPhSN946155CrmZ@flugo-db.flycast:5432"
  # REDIS_PORT = "redis://default:559c8e8b1c6441549530cc75d72b8199@fly-flugo-redis.upstash.io"
  REDIS_PORT = "fly-flugo-redis.upstash.io:6379"
  REDIS_USER = "default"
  REDIS_PASS = "559c8e8b1c6441549530cc75d72b8199"

[http_service]
  internal_port = 3000
  # force_https = true
  # auto_stop_machines = true
  # auto_start_machines = true
  # min_machines_running = 0
