# fly.toml app configuration file generated for flugo-api on 2023-06-07T21:33:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flugo-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  REDIS_PORT="fly-flugo-redis.upstash.io:6379"
  REDIS_USER="default"
  REDIS_PASS="75335fde38124af7841b89650792b52d"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
