// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// PasswordFramework is an autogenerated mock type for the PasswordFramework type
type PasswordFramework struct {
	mock.Mock
}

type PasswordFramework_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordFramework) EXPECT() *PasswordFramework_Expecter {
	return &PasswordFramework_Expecter{mock: &_m.Mock}
}

// CheckPassword provides a mock function with given fields: password, hashedPassword
func (_m *PasswordFramework) CheckPassword(password string, hashedPassword string) error {
	ret := _m.Called(password, hashedPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(password, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordFramework_CheckPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPassword'
type PasswordFramework_CheckPassword_Call struct {
	*mock.Call
}

// CheckPassword is a helper method to define mock.On call
//   - password string
//   - hashedPassword string
func (_e *PasswordFramework_Expecter) CheckPassword(password interface{}, hashedPassword interface{}) *PasswordFramework_CheckPassword_Call {
	return &PasswordFramework_CheckPassword_Call{Call: _e.mock.On("CheckPassword", password, hashedPassword)}
}

func (_c *PasswordFramework_CheckPassword_Call) Run(run func(password string, hashedPassword string)) *PasswordFramework_CheckPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordFramework_CheckPassword_Call) Return(_a0 error) *PasswordFramework_CheckPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordFramework_CheckPassword_Call) RunAndReturn(run func(string, string) error) *PasswordFramework_CheckPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: password
func (_m *PasswordFramework) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordFramework_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordFramework_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *PasswordFramework_Expecter) HashPassword(password interface{}) *PasswordFramework_HashPassword_Call {
	return &PasswordFramework_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *PasswordFramework_HashPassword_Call) Run(run func(password string)) *PasswordFramework_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordFramework_HashPassword_Call) Return(_a0 string, _a1 error) *PasswordFramework_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordFramework_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *PasswordFramework_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewPasswordFramework interface {
	mock.TestingT
	Cleanup(func())
}

// NewPasswordFramework creates a new instance of PasswordFramework. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPasswordFramework(t mockConstructorTestingTNewPasswordFramework) *PasswordFramework {
	mock := &PasswordFramework{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
